In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
dir_content = os.listdir()

In [5]:
dir_content = [filename for filename in dir_content if filename.find('enduro') > -1]

In [6]:
dir_content

['1524545416-enduro-v0.csv', '1524545592-enduro-v0.csv']

In [7]:
df = pd.read_csv(dir_content[0])

In [32]:
df[df.rewards > 0.0]

Empty DataFrame
Columns: [Unnamed: 0, actions-input, rewards]
Index: []

In [9]:
first_sequence = df['actions-input'][:316]

In [10]:
list_sequence = first_sequence.tolist()
treated_sequence = []
start = 0
incremental= 4
limit = 4
reversed_sequence = list_sequence[::-1]
#reversed_sequence[start:limit]
#reversed_sequence[limit+4:]
reversed_sequence_len = lambda: range(len(reversed_sequence))
for _ in reversed_sequence_len():
    done = not reversed_sequence[start:limit]
    if not done: treated_sequence.append(reversed_sequence[start:limit])
    reversed_sequence = reversed_sequence[limit+incremental:]
    start = start + incremental
    limit = limit + incremental
    if done: break
treated_sequence

[[8, 6, 7, 2],
 [0, 4, 3, 8],
 [4, 7, 6, 5],
 [1, 5, 1, 4],
 [2, 5, 8, 4],
 [0, 7, 3, 6],
 [3, 1, 3, 3],
 [7, 8, 6, 8],
 [4, 3, 5, 3],
 [0, 5, 2, 1],
 [3, 8, 6, 3]]

In [11]:
print('Produced length of output: {}'.format(len(treated_sequence)))

Produced length of output: 11


In [12]:
actions = np.array(treated_sequence)

In [13]:
actions

array([[8, 6, 7, 2],
       [0, 4, 3, 8],
       [4, 7, 6, 5],
       [1, 5, 1, 4],
       [2, 5, 8, 4],
       [0, 7, 3, 6],
       [3, 1, 3, 3],
       [7, 8, 6, 8],
       [4, 3, 5, 3],
       [0, 5, 2, 1],
       [3, 8, 6, 3]])

In [14]:
second_sequence = df['rewards'][:316]

In [15]:
list_sequence = second_sequence.tolist()
treated_sequence = []
start = 0
incremental = 4
limit = 4
reversed_sequence = list_sequence[::-1]
reversed_sequence_len = lambda: range(len(reversed_sequence))
for _ in reversed_sequence_len():
    done = not reversed_sequence[start:limit]
    if not done: treated_sequence.append(reversed_sequence[start:limit])
    reversed_sequence = reversed_sequence[limit+incremental:]
    start = start + incremental
    limit = limit + incremental
    if done: break
treated_sequence

[[0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0]]

In [16]:
print('Produced length of output: {}'.format(len(treated_sequence)))

Produced length of output: 11


In [17]:
rewards = np.array(treated_sequence)

In [18]:
rewards

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
import warnings; warnings.simplefilter('ignore')

In [20]:
from keras.models import Sequential

Using TensorFlow backend.


In [21]:
from keras.layers import Dense

In [22]:
from sklearn import model_selection

In [23]:
x, x_val, y, y_val = model_selection.train_test_split(rewards, actions, test_size=0.2, random_state=42)

In [24]:
model = Sequential()

In [25]:
model.add(Dense(4, input_shape=(4,)))

In [26]:
model.compile(optimizer='rmsprop', loss='mse')

In [27]:
model.fit(x, y, epochs=10, batch_size=32, validation_data=(x_val, y_val))

Train on 8 samples, validate on 3 samples
Epoch 1/10
8/8 [==============================] - 0s 13ms/step - loss: 24.5312 - val_loss: 23.0586
Epoch 2/10
8/8 [==============================] - 0s 274us/step - loss: 24.5034 - val_loss: 23.0406
Epoch 3/10
8/8 [==============================] - 0s 305us/step - loss: 24.4832 - val_loss: 23.0256
Epoch 4/10
8/8 [==============================] - 0s 304us/step - loss: 24.4663 - val_loss: 23.0123
Epoch 5/10
8/8 [==============================] - 0s 326us/step - loss: 24.4513 - val_loss: 23.0001
Epoch 6/10
8/8 [==============================] - 0s 334us/step - loss: 24.4376 - val_loss: 22.9887
Epoch 7/10
8/8 [==============================] - 0s 292us/step - loss: 24.4248 - val_loss: 22.9779
Epoch 8/10
8/8 [==============================] - 0s 352us/step - loss: 24.4126 - val_loss: 22.9676
Epoch 9/10
8/8 [==============================] - 0s 320us/step - loss: 24.4010 - val_loss: 22.9576
Epoch 10/10
8/8 [==============================] - 0s 298us

In [28]:
score = model.evaluate(x, y)

8/8 [==============================] - 0s 187us/step


In [29]:
score

24.378910064697266

In [30]:
model.predict(np.array([[2,5,1,0],[1,1,4,2]]))

array([[ 3.361495  , -5.505101  , -2.6514647 , -0.34251547],
       [ 4.267953  , -3.1263242 , -3.0491097 , -0.05232491]],
      dtype=float32)

In [31]:
#!python ../app.py --environment_name "Pong-v0" --output_stats_filename "pong-v0"