In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
dir_content = os.listdir()

In [50]:
dir_content = [filename for filename in dir_content if filename.find('pong') > -1]

In [51]:
dir_content

['1524378176-pong-ram-deterministic-v0.csv']

In [7]:
df = pd.read_csv(dir_content[0])

In [8]:
df.head()

Unnamed: 0  actions-input  rewards
0           0              0      0.0
1           1              0      0.0
2           2              0      0.0
3           3              3      0.0
4           4              2      0.0

In [9]:
df[df.rewards > 0.0]

Unnamed: 0  actions-input  rewards
216           216              3      1.0
997           997              3      1.0
3010         3010              0      1.0
3192         3192              1      1.0
3410         3410              0      1.0
5168         5168              3      1.0
6193         6193              5      1.0
7740         7740              4      1.0
9617         9617              5      1.0
10355       10355              2      1.0
10924       10924              0      1.0
11032       11032              3      1.0
11286       11286              0      1.0
12018       12018              3      1.0
12896       12896              0      1.0
15365       15365              2      1.0

In [10]:
df.head(217)

Unnamed: 0  actions-input  rewards
0             0              0      0.0
1             1              0      0.0
2             2              0      0.0
3             3              3      0.0
4             4              2      0.0
5             5              5      0.0
6             6              0      0.0
7             7              3      0.0
8             8              0      0.0
9             9              1      0.0
10           10              2      0.0
11           11              3      0.0
12           12              3      0.0
13           13              0      0.0
14           14              2      0.0
15           15              1      0.0
16           16              0      0.0
17           17              0      0.0
18           18              5      0.0
19           19              2      0.0
20           20              0      0.0
21           21              4      0.0
22           22              1      0.0
23           23              3      0.0
24           24              0      0.0
25           25              0      0.0
26           26              0      0.0
27           27              5      0.0
28           28              2      0.0
29           29              5      0.0
..          ...            ...      ...
187         187              3      0.0
188         188              3      0.0
189         189              3      0.0
190         190              0      0.0
191         191              1      0.0
192         192              0      0.0
193         193              1      0.0
194         194              5      0.0
195         195              3      0.0
196         196              0      0.0
197         197              3      0.0
198         198              2      0.0
199         199              1      0.0
200         200              1      0.0
201         201              1      0.0
202         202              5      0.0
203         203              5      0.0
204         204              0      0.0
205         205              5      0.0
206         206              5      0.0
207         207              4      0.0
208         208              5      0.0
209         209              0      0.0
210         210              4      0.0
211         211              3      0.0
212         212              3      0.0
213         213              1      0.0
214         214              5      0.0
215         215              3      0.0
216         216              3      1.0

[217 rows x 3 columns]

In [11]:
first_sequence = df['actions-input'][:317]

In [12]:
list_sequence = first_sequence.tolist()
treated_sequence = []
start = 0
incremental= 4
limit = 4
reversed_sequence = list_sequence[::-1]
#reversed_sequence[start:limit]
#reversed_sequence[limit+4:]
reversed_sequence_len = lambda: range(len(reversed_sequence))
for _ in reversed_sequence_len():
    done = not reversed_sequence[start:limit]
    if not done: treated_sequence.append(reversed_sequence[start:limit])
    reversed_sequence = reversed_sequence[limit+incremental:]
    start = start + incremental
    limit = limit + incremental
    if done: break
treated_sequence

[[1, 0, 1, 0],
 [1, 4, 4, 1],
 [5, 5, 0, 2],
 [2, 5, 1, 0],
 [2, 4, 0, 3],
 [3, 3, 5, 1],
 [2, 4, 0, 5],
 [1, 2, 3, 4],
 [4, 4, 0, 2],
 [1, 1, 4, 2],
 [0, 1, 2, 0]]

In [13]:
print('Produced length of output: {}'.format(len(treated_sequence)))

Produced length of output: 11


In [14]:
actions = np.array(treated_sequence)

In [15]:
actions

array([[1, 0, 1, 0],
       [1, 4, 4, 1],
       [5, 5, 0, 2],
       [2, 5, 1, 0],
       [2, 4, 0, 3],
       [3, 3, 5, 1],
       [2, 4, 0, 5],
       [1, 2, 3, 4],
       [4, 4, 0, 2],
       [1, 1, 4, 2],
       [0, 1, 2, 0]])

In [16]:
second_sequence = df['rewards'][:317]

In [17]:
list_sequence = second_sequence.tolist()
treated_sequence = []
start = 0
incremental = 4
limit = 4
reversed_sequence = list_sequence[::-1]
reversed_sequence_len = lambda: range(len(reversed_sequence))
for _ in reversed_sequence_len():
    done = not reversed_sequence[start:limit]
    if not done: treated_sequence.append(reversed_sequence[start:limit])
    reversed_sequence = reversed_sequence[limit+incremental:]
    start = start + incremental
    limit = limit + incremental
    if done: break
treated_sequence

[[-1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.0, -1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0]]

In [18]:
print('Produced length of output: {}'.format(len(treated_sequence)))

Produced length of output: 11


In [19]:
rewards = np.array(treated_sequence)

In [20]:
rewards

array([[-1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [21]:
import warnings; warnings.simplefilter('ignore')

In [22]:
from keras.models import Sequential

Using TensorFlow backend.


In [23]:
from keras.layers import Dense

In [24]:
from keras.layers import Activation

In [25]:
from sklearn import model_selection

In [26]:
x, x_val, y, y_val = model_selection.train_test_split(rewards, actions, test_size=0.2, random_state=42)

In [27]:
model = Sequential()

In [28]:
model.add(Dense(4, input_shape=(4,)))

In [29]:
model.add(Activation('relu'))

In [30]:
model.add(Dense(4))

In [31]:
model.add(Activation('sigmoid'))

In [32]:
model.add(Dense(4))

In [33]:
model.compile(optimizer='rmsprop', loss='mse')

In [34]:
model.fit(x, y, epochs=10, validation_data=(x_val, y_val))

Train on 8 samples, validate on 3 samples
Epoch 1/10
8/8 [==============================] - 0s 23ms/step - loss: 6.8860 - val_loss: 3.8338
Epoch 2/10
8/8 [==============================] - 0s 349us/step - loss: 6.8483 - val_loss: 3.8134
Epoch 3/10
8/8 [==============================] - 0s 379us/step - loss: 6.8212 - val_loss: 3.7964
Epoch 4/10
8/8 [==============================] - 0s 284us/step - loss: 6.7985 - val_loss: 3.7815
Epoch 5/10
8/8 [==============================] - 0s 295us/step - loss: 6.7785 - val_loss: 3.7679
Epoch 6/10
8/8 [==============================] - 0s 418us/step - loss: 6.7602 - val_loss: 3.7552
Epoch 7/10
8/8 [==============================] - 0s 343us/step - loss: 6.7432 - val_loss: 3.7432
Epoch 8/10
8/8 [==============================] - 0s 430us/step - loss: 6.7271 - val_loss: 3.7318
Epoch 9/10
8/8 [==============================] - 0s 387us/step - loss: 6.7117 - val_loss: 3.7209
Epoch 10/10
8/8 [==============================] - 0s 597us/step - loss: 6.69

In [35]:
score = model.evaluate(x, y)

8/8 [==============================] - 0s 133us/step


In [36]:
score

6.6825456619262695

In [44]:
model.predict(np.array([[2,5,1,0],[1,1,4,2]]))

array([[ 0.37288553,  0.08706434,  0.39861295,  0.03514653],
       [ 0.8745328 ,  0.5887309 ,  0.8690586 , -0.295183  ]],
      dtype=float32)

In [49]:
#!python ../app.py --environment_name "Pong-v0" --output_stats_filename "pong-v0"